name: farm_habit
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  dropdown_button2: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: Nunito Sans
      fonts:
        - asset: fonts/NunitoSans-ExtraLight.ttf
          weight: 200
        - asset: fonts/NunitoSans-Light.ttf
          weight: 300
        - asset: fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: fonts/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: fonts/NunitoSans-Bold.ttf
          weight: 700
        - asset: fonts/NunitoSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/NunitoSans-Black.ttf
          weight: 600
        - asset: fonts/NunitoSans-ExtraLightItalic.ttf
          style: italic
        - asset: fonts/NunitoSans-LightItalic.ttf
          style: italic
        - asset: fonts/NunitoSans-Italic.ttf
          style: italic
        - asset: fonts/NunitoSans-SemiBoldItalic.ttf
          style: italic
        - asset: fonts/NunitoSans-BoldItalic.ttf
          style: italic
        - asset: fonts/NunitoSans-ExtraBoldItalic.ttf
          style: italic
        - asset: fonts/NunitoSans-BlackItalic.ttf
          style: italic
